apiVersion: batch/v1
kind: Job
metadata:
  name: oe-helloworld
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: oe-helloworld
    spec:
      containers:
      - name: oe-helloworld
        image: oeciteam/oe-helloworld:1.0
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: "10"
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: "10"
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd
      restartPolicy: "Never"
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
  backoffLimit: 0
