CREATE TABLE IF NOT EXISTS citizen_registry (
    id SERIAL PRIMARY KEY,
    national_id VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    sex VARCHAR(10) NOT NULL,
    region VARCHAR(100) NOT NULL,
    municipality VARCHAR(100) NOT NULL,
    address_line VARCHAR(200),
    postal_code VARCHAR(10),
    household_size INTEGER DEFAULT 1,
    marital_status VARCHAR(20) DEFAULT 'Single',
    employment_status VARCHAR(30) DEFAULT 'Employed',
    tax_bracket VARCHAR(10) DEFAULT 'B',
    registered_voter BOOLEAN DEFAULT TRUE
);

INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2007-000001', 'Leif', 'Brekke', '2007-07-08', 'Male', 'Central Plains', 'Slettemarka', '193 Slettemarka Street', '76143', 2, 'Married', 'Retired', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1952-000002', 'Ingrid', 'Aasen', '1952-03-03', 'Female', 'Highland Province', 'Dalheim', '27 Dalheim Street', '75414', 6, 'Divorced', 'Self-Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1959-000003', 'Ylva', 'Lindqvist', '1959-09-17', 'Female', 'Southern Delta', 'Solvik', '34 Solvik Street', '39785', 5, 'Single', 'Retired', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1952-000004', 'Lars', 'Vik', '1952-01-27', 'Male', 'North Coast', 'Strandvik', '162 Strandvik Street', '20074', 5, 'Widowed', 'Retired', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1946-000005', 'Rolf', 'Moen', '1946-08-20', 'Male', 'Eastern Corridor', 'Grenseby', '109 Grenseby Street', '47808', 2, 'Married', 'Self-Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2006-000006', 'Ylva', 'Foss', '2006-09-16', 'Female', 'Highland Province', 'Dalheim', '259 Dalheim Street', '36154', 2, 'Divorced', 'Self-Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1987-000007', 'Gunnar', 'Hagen', '1987-03-18', 'Male', 'Eastern Corridor', 'Elvemo', '86 Elvemo Street', '61801', 1, 'Widowed', 'Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1951-000008', 'Per', 'Brekke', '1951-01-27', 'Male', 'North Coast', 'Strandvik', '224 Strandvik Street', '35993', 3, 'Single', 'Retired', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1969-000009', 'Gunnar', 'Fjeld', '1969-08-24', 'Male', 'Central Plains', 'Akerby', '95 Akerby Street', '92337', 5, 'Married', 'Employed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2004-000010', 'Harald', 'Moen', '2004-01-27', 'Male', 'Central Plains', 'Slettemarka', '151 Slettemarka Street', '64757', 8, 'Widowed', 'Self-Employed', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1972-000011', 'Liv', 'Moen', '1972-08-16', 'Female', 'Southern Delta', 'Deltastad', '104 Deltastad Street', '78576', 6, 'Widowed', 'Retired', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2002-000012', 'Lars', 'Aasen', '2002-03-01', 'Male', 'Eastern Corridor', 'Elvemo', '276 Elvemo Street', '95369', 1, 'Married', 'Retired', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1999-000013', 'Ingrid', 'Bakken', '1999-04-13', 'Female', 'Highland Province', 'Fjellstad', '228 Fjellstad Street', '32455', 3, 'Widowed', 'Unemployed', 'E', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1961-000014', 'Greta', 'Lindqvist', '1961-10-11', 'Female', 'Highland Province', 'Dalheim', '234 Dalheim Street', '82547', 2, 'Married', 'Unemployed', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1953-000015', 'Maja', 'Strand', '1953-12-18', 'Female', 'Central Plains', 'Akerby', '181 Akerby Street', '61272', 6, 'Widowed', 'Student', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1955-000016', 'Sigrid', 'Lindqvist', '1955-06-19', 'Female', 'Eastern Corridor', 'Elvemo', '80 Elvemo Street', '33914', 4, 'Married', 'Student', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1943-000017', 'Anja', 'Torp', '1943-05-04', 'Female', 'Eastern Corridor', 'Grenseby', '83 Grenseby Street', '15514', 7, 'Widowed', 'Student', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1994-000018', 'Hakon', 'Holm', '1994-06-20', 'Male', 'Highland Province', 'Fjellstad', '165 Fjellstad Street', '52761', 2, 'Married', 'Student', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1996-000019', 'Maja', 'Holm', '1996-03-25', 'Female', 'Eastern Corridor', 'Elvemo', '85 Elvemo Street', '20849', 1, 'Single', 'Retired', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1956-000020', 'Freya', 'Skog', '1956-09-21', 'Female', 'Central Plains', 'Akerby', '180 Akerby Street', '95016', 8, 'Widowed', 'Retired', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1941-000021', 'Ingrid', 'Lund', '1941-09-01', 'Female', 'Central Plains', 'Midtfjord', '10 Midtfjord Street', '58645', 4, 'Widowed', 'Self-Employed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1941-000022', 'Astrid', 'Skog', '1941-11-15', 'Female', 'Southern Delta', 'Sydport', '253 Sydport Street', '30193', 5, 'Single', 'Self-Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1967-000023', 'Knut', 'Vik', '1967-08-09', 'Male', 'Highland Province', 'Fjellstad', '207 Fjellstad Street', '44579', 1, 'Single', 'Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1988-000024', 'Anders', 'Brekke', '1988-04-04', 'Male', 'North Coast', 'Kystby', '278 Kystby Street', '94472', 6, 'Married', 'Employed', 'E', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1976-000025', 'Erik', 'Brekke', '1976-09-20', 'Male', 'Highland Province', 'Dalheim', '99 Dalheim Street', '27575', 2, 'Divorced', 'Retired', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2008-000026', 'Thora', 'Moen', '2008-08-04', 'Female', 'Central Plains', 'Slettemarka', '69 Slettemarka Street', '50844', 3, 'Divorced', 'Student', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1971-000027', 'Helga', 'Torp', '1971-07-01', 'Female', 'Eastern Corridor', 'Grenseby', '277 Grenseby Street', '56840', 3, 'Single', 'Unemployed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2003-000028', 'Rolf', 'Dahl', '2003-08-16', 'Male', 'Highland Province', 'Fjellstad', '209 Fjellstad Street', '62811', 4, 'Single', 'Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1977-000029', 'Harald', 'Haugen', '1977-05-18', 'Male', 'Highland Province', 'Bergvik', '297 Bergvik Street', '86026', 6, 'Married', 'Unemployed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1975-000030', 'Dag', 'Brekke', '1975-08-03', 'Male', 'Eastern Corridor', 'Grenseby', '202 Grenseby Street', '65782', 1, 'Divorced', 'Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1985-000031', 'Olav', 'Haugen', '1985-01-11', 'Male', 'North Coast', 'Strandvik', '166 Strandvik Street', '60945', 7, 'Single', 'Student', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2005-000032', 'Karin', 'Haugen', '2005-09-16', 'Female', 'Eastern Corridor', 'Elvemo', '109 Elvemo Street', '69335', 3, 'Widowed', 'Unemployed', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1952-000033', 'Anja', 'Haugen', '1952-07-17', 'Female', 'Southern Delta', 'Deltastad', '116 Deltastad Street', '23313', 4, 'Single', 'Student', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1989-000034', 'Rolf', 'Lindqvist', '1989-04-16', 'Male', 'Highland Province', 'Fjellstad', '175 Fjellstad Street', '91914', 7, 'Divorced', 'Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1977-000035', 'Eva', 'Foss', '1977-07-15', 'Female', 'Southern Delta', 'Deltastad', '257 Deltastad Street', '81525', 2, 'Divorced', 'Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1996-000036', 'Helga', 'Aasen', '1996-04-12', 'Female', 'Southern Delta', 'Solvik', '144 Solvik Street', '11666', 1, 'Married', 'Self-Employed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2007-000037', 'Sven', 'Moen', '2007-08-11', 'Male', 'Eastern Corridor', 'Grenseby', '20 Grenseby Street', '48649', 8, 'Single', 'Student', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1975-000038', 'Sigrid', 'Aasen', '1975-11-14', 'Female', 'Central Plains', 'Midtfjord', '52 Midtfjord Street', '12014', 8, 'Married', 'Self-Employed', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1976-000039', 'Dagny', 'Bakken', '1976-11-13', 'Female', 'Eastern Corridor', 'Elvemo', '159 Elvemo Street', '19299', 5, 'Married', 'Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1943-000040', 'Sven', 'Berg', '1943-06-12', 'Male', 'Southern Delta', 'Sydport', '252 Sydport Street', '46049', 5, 'Divorced', 'Retired', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1990-000041', 'Olav', 'Lindqvist', '1990-03-14', 'Male', 'Central Plains', 'Midtfjord', '50 Midtfjord Street', '66218', 6, 'Single', 'Self-Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1990-000042', 'Hilde', 'Foss', '1990-06-27', 'Female', 'Eastern Corridor', 'Elvemo', '15 Elvemo Street', '63562', 5, 'Widowed', 'Unemployed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1945-000043', 'Maja', 'Solberg', '1945-09-12', 'Female', 'Highland Province', 'Fjellstad', '242 Fjellstad Street', '98272', 8, 'Single', 'Student', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1942-000044', 'Thora', 'Vik', '1942-11-17', 'Female', 'Southern Delta', 'Solvik', '271 Solvik Street', '71457', 8, 'Married', 'Self-Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1952-000045', 'Maren', 'Aasen', '1952-09-20', 'Female', 'North Coast', 'Havnsund', '168 Havnsund Street', '53348', 3, 'Divorced', 'Unemployed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1961-000046', 'Britt', 'Solberg', '1961-11-24', 'Female', 'Highland Province', 'Dalheim', '144 Dalheim Street', '34595', 7, 'Married', 'Employed', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1991-000047', 'Leif', 'Brekke', '1991-07-27', 'Male', 'Eastern Corridor', 'Grenseby', '84 Grenseby Street', '75603', 1, 'Married', 'Retired', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1949-000048', 'Nils', 'Hagen', '1949-01-11', 'Male', 'North Coast', 'Kystby', '244 Kystby Street', '39040', 6, 'Married', 'Self-Employed', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2001-000049', 'Anders', 'Aasen', '2001-10-08', 'Male', 'Highland Province', 'Fjellstad', '238 Fjellstad Street', '84907', 8, 'Single', 'Student', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1943-000050', 'Sven', 'Vik', '1943-02-21', 'Male', 'Central Plains', 'Midtfjord', '38 Midtfjord Street', '12817', 4, 'Widowed', 'Self-Employed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1945-000051', 'Lars', 'Foss', '1945-03-08', 'Male', 'Highland Province', 'Dalheim', '186 Dalheim Street', '74822', 7, 'Widowed', 'Student', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1968-000052', 'Gunnar', 'Solberg', '1968-02-02', 'Male', 'Central Plains', 'Slettemarka', '124 Slettemarka Street', '56640', 2, 'Widowed', 'Employed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2003-000053', 'Nils', 'Torp', '2003-03-13', 'Male', 'Southern Delta', 'Sydport', '145 Sydport Street', '37015', 6, 'Single', 'Self-Employed', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1953-000054', 'Gunnar', 'Strand', '1953-10-27', 'Male', 'Eastern Corridor', 'Grenseby', '167 Grenseby Street', '32885', 4, 'Single', 'Unemployed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1942-000055', 'Sigrid', 'Skog', '1942-11-12', 'Female', 'North Coast', 'Havnsund', '52 Havnsund Street', '78612', 6, 'Single', 'Student', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1968-000056', 'Solveig', 'Dahl', '1968-02-01', 'Female', 'Highland Province', 'Fjellstad', '294 Fjellstad Street', '78441', 2, 'Widowed', 'Student', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1975-000057', 'Britt', 'Nordberg', '1975-11-22', 'Female', 'Highland Province', 'Fjellstad', '197 Fjellstad Street', '24152', 3, 'Widowed', 'Self-Employed', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2008-000058', 'Erik', 'Lund', '2008-09-09', 'Male', 'Highland Province', 'Dalheim', '188 Dalheim Street', '70732', 4, 'Single', 'Student', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1969-000059', 'Harald', 'Torp', '1969-07-04', 'Male', 'Central Plains', 'Midtfjord', '103 Midtfjord Street', '53373', 2, 'Married', 'Retired', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1962-000060', 'Helga', 'Bakken', '1962-06-06', 'Female', 'Highland Province', 'Bergvik', '116 Bergvik Street', '39775', 7, 'Divorced', 'Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1940-000061', 'Greta', 'Moen', '1940-03-13', 'Female', 'Southern Delta', 'Sydport', '115 Sydport Street', '25176', 1, 'Married', 'Employed', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1945-000062', 'Per', 'Bakken', '1945-08-11', 'Male', 'Southern Delta', 'Solvik', '164 Solvik Street', '74436', 7, 'Single', 'Self-Employed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1978-000063', 'Maren', 'Bakken', '1978-09-16', 'Female', 'Highland Province', 'Bergvik', '167 Bergvik Street', '51428', 4, 'Single', 'Employed', 'E', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2004-000064', 'Thora', 'Moen', '2004-12-06', 'Female', 'Southern Delta', 'Solvik', '219 Solvik Street', '88581', 7, 'Widowed', 'Unemployed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1958-000065', 'Karin', 'Hagen', '1958-11-20', 'Female', 'Eastern Corridor', 'Ostvik', '242 Ostvik Street', '69394', 2, 'Widowed', 'Employed', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1981-000066', 'Bjorn', 'Berg', '1981-06-09', 'Male', 'Southern Delta', 'Solvik', '220 Solvik Street', '78836', 3, 'Married', 'Self-Employed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1980-000067', 'Freya', 'Dahl', '1980-12-07', 'Female', 'Eastern Corridor', 'Grenseby', '57 Grenseby Street', '91950', 4, 'Widowed', 'Retired', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1984-000068', 'Sven', 'Nordberg', '1984-04-06', 'Male', 'Eastern Corridor', 'Ostvik', '246 Ostvik Street', '43464', 2, 'Single', 'Employed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1984-000069', 'Hilde', 'Hagen', '1984-10-05', 'Female', 'Central Plains', 'Akerby', '298 Akerby Street', '16693', 2, 'Single', 'Self-Employed', 'E', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1993-000070', 'Anja', 'Vik', '1993-02-08', 'Female', 'Central Plains', 'Akerby', '159 Akerby Street', '66900', 4, 'Widowed', 'Student', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1973-000071', 'Anders', 'Aasen', '1973-12-06', 'Male', 'North Coast', 'Strandvik', '296 Strandvik Street', '45814', 7, 'Widowed', 'Student', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1949-000072', 'Sven', 'Foss', '1949-04-27', 'Male', 'Eastern Corridor', 'Elvemo', '277 Elvemo Street', '60907', 8, 'Divorced', 'Unemployed', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1999-000073', 'Per', 'Holm', '1999-03-18', 'Male', 'Central Plains', 'Midtfjord', '146 Midtfjord Street', '78575', 7, 'Married', 'Unemployed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1992-000074', 'Thora', 'Torp', '1992-10-12', 'Female', 'North Coast', 'Strandvik', '201 Strandvik Street', '79394', 3, 'Widowed', 'Retired', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1940-000075', 'Maren', 'Brekke', '1940-11-23', 'Female', 'Central Plains', 'Midtfjord', '161 Midtfjord Street', '22525', 5, 'Single', 'Self-Employed', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1990-000076', 'Dagny', 'Sund', '1990-07-26', 'Female', 'North Coast', 'Strandvik', '8 Strandvik Street', '41162', 5, 'Married', 'Student', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1980-000077', 'Dagny', 'Brekke', '1980-09-26', 'Female', 'Highland Province', 'Dalheim', '70 Dalheim Street', '91326', 8, 'Divorced', 'Self-Employed', 'E', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1952-000078', 'Gunnar', 'Brekke', '1952-06-25', 'Male', 'Southern Delta', 'Solvik', '277 Solvik Street', '86439', 8, 'Divorced', 'Student', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1974-000079', 'Ingrid', 'Skog', '1974-11-27', 'Female', 'Highland Province', 'Fjellstad', '299 Fjellstad Street', '93810', 5, 'Divorced', 'Self-Employed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1950-000080', 'Thora', 'Bakken', '1950-02-01', 'Female', 'Eastern Corridor', 'Elvemo', '262 Elvemo Street', '86829', 1, 'Divorced', 'Self-Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1953-000081', 'Runa', 'Solberg', '1953-02-25', 'Female', 'Southern Delta', 'Solvik', '270 Solvik Street', '18586', 1, 'Widowed', 'Retired', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1948-000082', 'Bjorn', 'Berg', '1948-07-22', 'Male', 'Southern Delta', 'Sydport', '232 Sydport Street', '32123', 8, 'Single', 'Retired', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2008-000083', 'Maja', 'Lindqvist', '2008-11-28', 'Female', 'North Coast', 'Havnsund', '271 Havnsund Street', '12607', 6, 'Married', 'Employed', 'C', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1985-000084', 'Knut', 'Lindqvist', '1985-01-22', 'Male', 'Highland Province', 'Fjellstad', '160 Fjellstad Street', '97378', 4, 'Single', 'Student', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1971-000085', 'Astrid', 'Torp', '1971-06-08', 'Female', 'Southern Delta', 'Solvik', '50 Solvik Street', '93758', 3, 'Divorced', 'Unemployed', 'A', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1989-000086', 'Rolf', 'Holm', '1989-08-26', 'Male', 'Highland Province', 'Dalheim', '282 Dalheim Street', '19222', 1, 'Single', 'Unemployed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1977-000087', 'Arne', 'Brekke', '1977-04-27', 'Male', 'Southern Delta', 'Sydport', '15 Sydport Street', '95576', 7, 'Divorced', 'Unemployed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2006-000088', 'Per', 'Bakken', '2006-02-15', 'Male', 'Central Plains', 'Midtfjord', '202 Midtfjord Street', '30217', 8, 'Married', 'Unemployed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1995-000089', 'Greta', 'Foss', '1995-04-14', 'Female', 'North Coast', 'Kystby', '159 Kystby Street', '61196', 2, 'Single', 'Employed', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1991-000090', 'Hilde', 'Berg', '1991-08-28', 'Female', 'Central Plains', 'Akerby', '264 Akerby Street', '49637', 2, 'Divorced', 'Student', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2005-000091', 'Nils', 'Bakken', '2005-11-04', 'Male', 'Southern Delta', 'Deltastad', '117 Deltastad Street', '39917', 3, 'Single', 'Self-Employed', 'E', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2006-000092', 'Erik', 'Aasen', '2006-02-24', 'Male', 'Highland Province', 'Bergvik', '122 Bergvik Street', '84680', 6, 'Single', 'Unemployed', 'D', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2005-000093', 'Astrid', 'Torp', '2005-05-15', 'Female', 'Southern Delta', 'Solvik', '98 Solvik Street', '37335', 4, 'Single', 'Unemployed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1986-000094', 'Freya', 'Hagen', '1986-04-02', 'Female', 'Highland Province', 'Dalheim', '61 Dalheim Street', '16774', 2, 'Divorced', 'Student', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1956-000095', 'Rolf', 'Nordberg', '1956-12-02', 'Male', 'Southern Delta', 'Solvik', '127 Solvik Street', '36783', 8, 'Widowed', 'Self-Employed', 'A', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1966-000096', 'Gunnar', 'Dahl', '1966-08-04', 'Male', 'Highland Province', 'Dalheim', '202 Dalheim Street', '96547', 2, 'Divorced', 'Self-Employed', 'B', FALSE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1944-000097', 'Dag', 'Strand', '1944-07-15', 'Male', 'Southern Delta', 'Solvik', '195 Solvik Street', '28495', 2, 'Single', 'Unemployed', 'B', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1942-000098', 'Nils', 'Lindqvist', '1942-11-11', 'Male', 'Eastern Corridor', 'Grenseby', '100 Grenseby Street', '57503', 8, 'Married', 'Retired', 'C', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-1967-000099', 'Anders', 'Skog', '1967-11-16', 'Male', 'Central Plains', 'Slettemarka', '253 Slettemarka Street', '72147', 7, 'Widowed', 'Self-Employed', 'D', TRUE);
INSERT INTO citizen_registry (national_id, first_name, last_name, date_of_birth, sex, region, municipality, address_line, postal_code, household_size, marital_status, employment_status, tax_bracket, registered_voter) VALUES ('NOR-2002-000100', 'Anja', 'Torp', '2002-06-02', 'Female', 'Southern Delta', 'Deltastad', '63 Deltastad Street', '45610', 6, 'Single', 'Unemployed', 'D', TRUE);
