---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: default
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 128; }
    http {
      server {
        listen 8081;
        location / {
          proxy_pass http://172.16.0.5:80/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
      server {
        listen 8082;
        location / {
          proxy_pass http://172.16.0.4:80/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
      server {
        listen 8083;
        location / {
          proxy_pass http://172.16.0.6:80/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: nginx-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: contoso
      port: 8081
      targetPort: 8081
    - name: fabrikam
      port: 8082
      targetPort: 8082
    - name: woodgrove
      port: 8083
      targetPort: 8083
