apiVersion: v1
kind: Service
metadata:
  name: attested-tls-service
  namespace: default
spec:
  ports:
  - name: client1
    port: 12341
    targetPort: 12341
  selector:
    app: attested-tls-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attested-tls-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attested-tls-server
  template:
    metadata:
      labels:
        app: attested-tls-server
    spec:
      containers:
      - name: attested-tls-server-demo
        image: oeciteam/oe-attested-tls:1.0
        command: ["./server/host/tls_server_host", "./server/enc/tls_server_enc.signed", "-port:12341"]
        volumeMounts:
        - name: var-run-aesmd
          mountPath: /var/run/aesmd # hardcoded in intels libarary, volume name must match that of the daemonset 
        ports:
        - name: client1
          containerPort: 12341
        imagePullPolicy: Always
        resources:
          limits:
            sgx.intel.com/epc: "10Mi"
          requests:
            sgx.intel.com/epc: "10Mi"
      # restartPolicy: "Never"
      volumes:
      - name: var-run-aesmd
        hostPath:
          path: /var/run/aesmd
