apiVersion: batch/v1
kind: Job
metadata:
  name: attested-tls-client
spec:
  template:
    metadata:
      labels:
        app: attested-tls-client
    spec:
      containers:
      - name: attested-tls-client
        image: oeciteam/attested_tls:1.0
        command: ["./non_enc_client/tls_non_enc_client"]
        env:
          - name: SGX_AESM_ADDR
            value: 1
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 5
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 5
        args:
        - -server:<server IP here>
        - -port:12341
      restartPolicy: "Never"
  backoffLimit: 0
  