apiVersion: batch/v1
kind: Job
metadata:
  name: sgx-test
spec:
  template:
    metadata:
      labels:
        app: sgx-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - acc
                - acc_second
      containers:
      - name: sgx-test
        image: oeciteam/oe-helloworld:1.0
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
          requests:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
      restartPolicy: "Never"
  backoffLimit: 0