name: Secret Scan

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - sov-example-1

jobs:
  scan:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Run repository secret scan
        shell: pwsh
        run: ./scripts/pre-commit.ps1 -ScanMode all